In [1]:
import numpy as np
A = np.arange(1, 21).reshape(4, 5)

print("A:\n", A)
print("Data type:", A.dtype)
print("Dimensions:", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Item size (bytes):", A.itemsize)
print("Total size (bytes):", A.nbytes)

B = A.reshape(5, 4)
print("B :\n", B)


A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Data type: int64
Dimensions: 2
Shape: (4, 5)
Size: 20
Item size (bytes): 8
Total size (bytes): 160
B :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [2]:
import numpy as np

a = np.array([[0.,0.,0.],
              [10.,10.,10.],
              [20.,20.,20.],
              [30.,30.,30.]])

b = np.array([0., 1., 2.])

c = a + b
print("a + b:")
print(c)

mask = (c >= 22)
print("Mask (c >= 22):")
print( mask)

count = np.sum(mask)
print("Count of values >= 22:", count) 



a + b:
[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]
Mask (c >= 22):
[[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]]
Count of values >= 22: 4


In [3]:
import numpy as np

grades = np.array([[87, 96, 70],
                   [100, 87, 90],
                   [94, 77, 90],
                   [100, 81, 82]])
print("Sum:", np.sum(grades))
print("Min:", np.min(grades))
print("Max:", np.max(grades))
print("Mean:", np.mean(grades))
print("Std:", np.std(grades))
print("Var:", np.var(grades))

print("Mean per column:", np.mean(grades, axis=0))
print("Mean per row:", np.mean(grades, axis=1))
print("Max per row:", np.max(grades, axis=1))


Sum: 1054
Min: 70
Max: 100
Mean: 87.83333333333333
Std: 8.792357792739987
Var: 77.30555555555556
Mean per column: [95.25 85.25 83.  ]
Mean per row: [84.33333333 92.33333333 87.         87.66666667]
Max per row: [ 96 100  94 100]


In [4]:
import numpy as np

arr = np.array([[2, 4, 6],
                [1, 3, 5],
                [7, 9, 11]])

print("Array:\n", arr)
print("Sum of each row:", np.sum(arr, axis=1))
print("Sum of each column:", np.sum(arr, axis=0))
print("Overall mean:", np.mean(arr))



Array:
 [[ 2  4  6]
 [ 1  3  5]
 [ 7  9 11]]
Sum of each row: [12  9 27]
Sum of each column: [10 16 22]
Overall mean: 5.333333333333333


In [5]:
import numpy as np

A = np.array([[10, 20, 30],
              [40, 50, 60]])

B = np.array([1, 2, 3])

print("A + B:\n", A + B)
print("A * 2:\n", A * 2)
print("A - 5:\n", A - 5)


A + B:
 [[11 22 33]
 [41 52 63]]
A * 2:
 [[ 20  40  60]
 [ 80 100 120]]
A - 5:
 [[ 5 15 25]
 [35 45 55]]


In [6]:
import numpy as np

grades = np.array([[70, 85, 90],
                   [88, 76, 95],
                   [60, 80, 72]])

print("\nIndex of largest value in whole array:",
      np.argmax(grades))

print("Index of highest grade in each row:",
      np.argmax(grades, axis=1))

print("Index of lowest grade in each column:",
      np.argmin(grades, axis=0))




Index of largest value in whole array: 5
Index of highest grade in each row: [2 2 1]
Index of lowest grade in each column: [2 1 2]
