In [5]:
import numpy as np 
M=np.array([[5,8,2,7], [1,9,4,3], [6,0,11,10],[11,12,13,14]]) 
 
print("The second row \n", M[1]) 
 
print("The third column  \n", M[:,2]) 
 
print("The sub-table  \n", M[2:4,2:4]) 

The second row 
 [1 9 4 3]
The third column  
 [ 2  4 11 13]
The sub-table  
 [[11 10]
 [13 14]]


In [1]:
import numpy as np 
M=np.array([[70,80,90], [60,75,85], [88,92,79],[55,65,72]]) 
print("All Values\n",M) 

M[:,1]+=5 
print("crease all Physics marks by +5\n" ,M[:,1]), 
 
M[0]=100 
print("first student's marks\n",M[0]) 

M[:,2]=0 
print("he last column (CS)\n",M[:,2]) 

All Values
 [[70 80 90]
 [60 75 85]
 [88 92 79]
 [55 65 72]]
crease all Physics marks by +5
 [85 80 97 70]
first student's marks
 [100 100 100]
he last column (CS)
 [0 0 0 0]


In [2]:
import numpy as np 
A = np.array([[1, 2],  
[3, 4]])  
B = np.array([[5, 6],  
[7, 8]])  
v = np.array([2, 4]) 
R=A*B 
print("element-wise multiplication A * B \n",R); 
R=A@B 
print("matrix multiplication A @ B \n",R) 

R=A*v 
print("A * v using broadcasting \n",R)

element-wise multiplication A * B 
 [[ 5 12]
 [21 32]]
matrix multiplication A @ B 
 [[19 22]
 [43 50]]
A * v using broadcasting 
 [[ 2  8]
 [ 6 16]]


In [4]:
import numpy as np 
np.random.seed(55) 
M=np.random.randint(-5,5,size=(4,4)) 
print(M) 
UN,Counts=np.unique(M, return_counts=True) 
print("the unique values in the matrix : ", UN) 
print("the count of each unique value : ",Counts) 
 
a = np.array([[1, 0, 0],  
              [1, 0, 0],  
              [2, 3, 4]]) 
UN2=np.unique(M, axis=0) 
print("this 2-D array, return unique rows : ",UN2) 

[[ 2  3  0  2]
 [ 0 -4  1 -5]
 [-2  3  2 -4]
 [ 0  2  3 -2]]
the unique values in the matrix :  [-5 -4 -2  0  1  2  3]
the count of each unique value :  [1 2 2 3 1 4 3]
this 2-D array, return unique rows :  [[-2  3  2 -4]
 [ 0 -4  1 -5]
 [ 0  2  3 -2]
 [ 2  3  0  2]]


In [3]:
import numpy as np  
x = np.array([2, 0, 1, 5, 4, 1, 9])  
A = np.array([[3, 8, 1],  
[6, 2, 9]])  
XX=np.argsort(x) 
print(XX) 

mini=np.unravel_index(A.argmin(), A.shape) 
print("minimum indix  \n " , mini, " \nminimum value :",A[mini])

[1 2 5 0 4 3 6]
minimum indix  
  (np.int64(0), np.int64(2))  
minimum value : 1
